name       : kjs
version    : 5.106.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/portingAids/kjs-5.106.0.tar.xz : 82bf295b3ff863e98ffec6756e6449313c39b747917ad200c41b1c729bfd5249
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - pkgconfig(libpcre)
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
