name       : kjs
version    : 5.93.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/portingAids/kjs-5.93.0.tar.xz : 85aa01de9c2775564c895d3efbcfb8cc68da9a84f511176fef16742cbbf90942
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - pkgconfig(libpcre)
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
