name       : kjs
version    : 5.66.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/portingAids/kjs-5.66.0.tar.xz : 9bed62ebf9fba7d986ff7baabf6c4431f02826c9be70beda15cc62c692fb5f7f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
