name       : kjs
version    : 5.50.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/portingAids/kjs-5.50.0.tar.xz : bbd30041fd953fc0908cfc423f56ff701fb9a1ce5a5c885f748cd722ce63cdc9
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
