name       : kjs
version    : 5.90.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/portingAids/kjs-5.90.0.tar.xz : 9bab652cadbc3be62d477ac07a7aa0fae296db2ab042097aea06abfd7b0cadfc
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - pkgconfig(libpcre)
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
