name       : kjs
version    : 5.45.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/portingAids/kjs-5.45.0.tar.xz : 5917480144dc1c45f80c11f8652e6cc9b4f73d0f3ad77fc1dc2299b1dd29acf6
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
