name       : kjs
version    : 5.80.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/portingAids/kjs-5.80.0.tar.xz : 3286281f3ebbfc78336cff73a012106f836f39b7ef1ed32e6040c4ffb98f72ec
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - pkgconfig(libpcre)
    - kdoctools-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
