name       : kjs
version    : 5.44.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/portingAids/kjs-5.44.0.tar.xz : 1e46643b0cb189db98aa5cec46751d259e5589f48b7eab3ea738ddd85f0765f8
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Javascript engine for KDE
description: |
    This library provides an ECMAScript compatible interpreter. The ECMA standard is based on well known scripting languages such as Netscape's JavaScript and Microsoft's JScript.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
